"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.conf.global_settings import AUTH_USER_MODEL
from import_export.formats.base_formats import XLSX
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config('DEBUG', default=False, cast=bool)
# ALLOWED_HOSTS = [config('ALLOWED_HOSTS')]
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'nested_admin',
    #celery
    'django_celery_results',
    'django_celery_beat',
    #apps
    'projectapp.apps.ProjectappConfig',
    'usersapp.apps.UsersappConfig',
    'feedbackapp.apps.FeedbackappConfig',
    'frontendapp.apps.FrontendappConfig',
    #export data as xlsx (also CSV and json)
    'import_export',
    'rangefilter'
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%d-%m-%Y'],
}

BASE_ADDRESS_OF_PDFS_ON_SERVER = config('BASE_ADDRESS_OF_PDFS_ON_SERVER')

# ------------ celery ---------------------------------
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_IMPORTS = (
    'projectapp.tasks',
)
# -------------------------------------------------------

EXPORT_FORMATS = [XLSX]
AUTH_USER_MODEL = 'usersapp.CustomUserModel'
AUTHENTICATION_BACKENDS = ["usersapp.backends.UsernameBackend"]
# ---------------------------------------------------------
LOGIN_URL = '/users/login/'
# LOGIN_REDIRECT_URL

# -----------------------------------------------------------

# SESSION_COOKIE_AGE = 0   # یعنی سشن فقط تا وقتی مرورگر بازه معتبره
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# ------------------------------------------------------------
# --------------------- cache --------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}

# ----------------------------- LOGGING ---------------------------

# -----------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ------------------------- logger --------------------------
LOGGING = {
    'version': 1, 
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            # هندلر برای نمایش لاگ‌ها در ترمینال
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file_celery': {
            # هندلر اصلی برای ذخیره لاگ‌های Celery در فایل
            'level': 'INFO', # فقط پیام‌های INFO و بالاتر را ذخیره کن
            'class': 'logging.handlers.RotatingFileHandler',
            # مسیر و نام فایل لاگ (در کنار BASE_DIR)
            'filename': str(BASE_DIR / 'logs' / 'celery_tasks.log'),
            'maxBytes': 1024 * 1024 * 5,  # حداکثر حجم فایل 5 مگابایت
            'backupCount': 5, # 5 فایل لاگ پشتیبان نگه دار
            'formatter': 'verbose',
        },
    },

    'loggers': {
        'django': {
            # لاگر پیش‌فرض جنگو (برای خطاهای سرور و ...)
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'projectapp.tasks': {
            # لاگر مخصوص تسک‌های Celery شما
            'handlers': ['console', 'file_celery'], # هم در کنسول نمایش داده شود و هم در فایل ذخیره گردد
            'level': 'INFO',
            'propagate': False, # از ارسال لاگ‌ها به لاگرهای والد جلوگیری می‌کند
        },
        # '': { 
        #     'handlers': ['console', 'file_celery'],
        #     'level': 'INFO',
        #     'propagate': True,
        # }
    },
}
# -----------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEIDA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
